### ISSUE TITLE
Maven build fails on JDK 1.8

### ISSUE THREAD

**Issue by fernandobrito** [crawljax/crawljax#484]
Trying to build master branch (currently on 9cb52ad3) on latest Ubuntu with JDK 1.8 gives some errors. Here is my report:

First I had this error:
```
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.222 sec <<< FAILURE! - in com.crawljax.core.state.StateFlowGraphTest
largetTest(com.crawljax.core.state.StateFlowGraphTest)  Time elapsed: 0.112 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: a collection with size <2>
     but: collection size was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.crawljax.core.state.StateFlowGraphTest.largetTest(StateFlowGraphTest.java:266)
```

No idea what causes this. If ignore this test case, I get an error related to javadocs:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project crawljax-core: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
[ERROR] /home/brito/salt/crawljax/core/src/main/java/com/crawljax/forms/FormInputValueHelper.java:243: error: bad use of '>'
[ERROR] *            the i-th specified value. if i>#values, first value is used
```

It seems all < and > signs on javadocs comments should be replaced with \&gt; and \&lt;, even the ones on "@author Name \<email\>"

**Comment by MartinRogalla** [comment]
Facing the same problems on OSX. I tried to skip the tests. This worked, but then it got stuck on the JavaDoc generation. Skipped that, now it successfully builds.

```
mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
```
