### ISSUE TITLE
java.lang.IllegalStateException when running new Configuration

### ISSUE THREAD

**Issue by Bisconcini** [crawljax/crawljax#491]
HI folks, I don't know if I miss something:
I have downloaded the release 3.5 for test --- following that instructions for testing: http://crawljax.com/blog/2014/03/07/crawljax-gets-a-face-lift-web-ui-in-crawljax-3-dot-5/ --- and I have got this IllegalStateException when I tried to "run a Configuration". The new configuration that I created was just a basic one. No plugins, no Crawl Rules, nothing. No matter what browser I choose, I get this:

    java -jar crawljax-web-3.6.jar 
	[pool-1-thread-1] ERROR com.crawljax.browser.WebDriverBrowserBuilder - Crawling with     CHROME failed: The path to the driver executable must be set by the webdriver.chrome.driver    system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver.    The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	com.google.inject.ProvisionException: Guice provision errors:

	1) Error in custom provider, java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	  while locating com.crawljax.browser.WebDriverBrowserBuilder
	  while locating com.crawljax.browser.EmbeddedBrowser
	    for parameter 0 at com.crawljax.core.CrawlerContext.<init>(CrawlerContext.java:32)
	  while locating com.crawljax.core.CrawlerContext
	    for parameter 0 at com.crawljax.core.Crawler.<init>(Crawler.java:73)
	  while locating com.crawljax.core.Crawler
	    for parameter 2 at com.crawljax.core.CrawlTaskConsumer.<init>(CrawlTaskConsumer.java:30)
	  while locating com.crawljax.core.CrawlTaskConsumer

	1 error
		at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
		at com.crawljax.core.CrawlController.call(CrawlController.java:65)
		at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37)
		at com.crawljax.web.runner.CrawlRunner$CrawlExecution.run(CrawlRunner.java:261)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
		at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
		at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
		at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:105)
		at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:89)
		at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:117)
		at com.crawljax.browser.WebDriverBrowserBuilder.newChromeBrowser(WebDriverBrowserBuilder.java:133)
		at com.crawljax.browser.WebDriverBrowserBuilder.get(WebDriverBrowserBuilder.java:68)
		at com.crawljax.browser.WebDriverBrowserBuilder.get(WebDriverBrowserBuilder.java:26)
		at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
		at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
		at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
		at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
		at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
		at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
		at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
		at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
		at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
		... 8 more

 Is it a bug or I miss something? I'm running in a CentOS. I have the Chrome installed, the firefox installed, and seems that the location of the browsers are right with the default ones.

**Comment by TobEnd** [comment]
Try setting the system-property like this

`System.setProperty("webdriver.chrome.driver", "./path/to/chromedriver");`
