### ISSUE TITLE
Problem with OpenCV While Running Crawljax on Apple M2 Chip

### ISSUE THREAD

**Issue by mobinashb** [crawljax/crawljax#532]
I'm trying to run Crawljax on an M2 Mac (MacOS Ventura, Java 1.8.0) but it keeps giving an error related to OpenCV. I'm having this problem with both the version on Maven and the one downloaded from the GitHub repository. The error message is as below:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1258)
	at org.bytedeco.javacpp.Loader.load(Loader.java:999)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:950)
	at org.bytedeco.javacpp.Loader.load(Loader.java:907)
	at com.crawljax.stateabstractions.visual.imagehashes.DHash.<clinit>(DHash.java:23)
	at com.crawljax.stateabstractions.visual.imagehashes.DHashStateVertexFactory.newStateVertex(DHashStateVertexFactory.java:38)
	at com.crawljax.core.state.StateVertexFactory.createIndex(StateVertexFactory.java:28)
	at com.crawljax.core.Crawler.crawlIndex(Crawler.java:633)
	at com.crawljax.core.CrawlTaskConsumer.crawlIndex(CrawlTaskConsumer.java:88)
	at com.crawljax.core.CrawlController.call(CrawlController.java:69)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:59)
```

I've tried different versions of Java and also tried downloading OpenCV and setting the directory containing the `.dylib` file as `java.library.path`, but it didn't solve the problem. I also tried adding 
```java
System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
```
but got another error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java343 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
```

**Comment by yrahulkr** [comment]
OpenCV support for Apple Silicon is not yet available in a maven release. However, as a temporary fix, users can use the `1.5.9-SNAPSHOT` build from [here](http://bytedeco.org/builds/). 

In order to use the SNAPSHOT release, please replace the `opencv` dependency in `crawljax/pom.xml`
