### ISSUE TITLE
Crawl overview failure

### ISSUE THREAD

**Issue by sinha108** [crawljax/crawljax#560]
**Describe the bug**

Running Crawljax 5.0 after building a fat jar (with all dependencies) gives this error:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonIgnoreProperties$Value com.fasterxml.jackson.databind.AnnotationIntrospector.findPropertyIgnoralByName(com.fasterxml.jackson.databind.cfg.MapperConfig, com.fasterxml.jackson.databind.introspect.Annotated)'
	at com.fasterxml.jackson.datatype.guava.ser.MultimapSerializer.createContextual(MultimapSerializer.java:206)
	at com.fasterxml.jackson.databind.SerializerProvider.handlePrimaryContextualization(SerializerProvider.java:976)
	at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:651)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:72)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:895)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:705)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1135)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1005)
	at com.crawljax.plugins.crawloverview.model.Serializer.toPrettyJson(Serializer.java:65)
	at com.crawljax.plugins.crawloverview.OutputBuilder.writeIndexFile(OutputBuilder.java:195)
	at com.crawljax.plugins.crawloverview.OutputBuilder.write(OutputBuilder.java:161)
	at com.crawljax.plugins.crawloverview.CrawlOverview.postCrawling(CrawlOverview.java:215)
	at com.crawljax.core.plugin.Plugins.runPostCrawlingPlugins(Plugins.java:210)
	at com.crawljax.core.CrawlController.executeConsumers(CrawlController.java:132)
	at com.crawljax.core.CrawlController.call(CrawlController.java:81)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:57)
	at org.konveyor.tackletest.ui.crawljax.CrawljaxRunner.main(CrawljaxRunner.java:753)
```

**Comment by sinha108** [comment]
I tried it again after the fix, and the fat jar built from a project with Crawljax dependency (https://github.com/konveyor/tackle-test-generator-core/tree/main/tackle-test-generator-ui) still fails with the same error:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonIgnoreProperties$Value com.fasterxml.jackson.databind.AnnotationIntrospector.findPropertyIgnoralByName(com.fasterxml.jackson.databind.cfg.MapperConfig, com.fasterxml.jackson.databind.introspect.Annotated)'
	at com.fasterxml.jackson.datatype.guava.ser.MultimapSerializer.createContextual(MultimapSerializer.java:206)
	at com.fasterxml.jackson.databind.SerializerProvider.handlePrimaryContextualization(SerializerProvider.java:976)
	at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:651)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:72)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:895)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:705)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1135)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1005)
	at com.crawljax.plugins.crawloverview.model.Serializer.toPrettyJson(Serializer.java:65)
	at com.crawljax.plugins.crawloverview.OutputBuilder.writeIndexFile(OutputBuilder.java:193)
	at com.crawljax.plugins.crawloverview.OutputBuilder.write(OutputBuilder.java:159)
	at com.crawljax.plugins.crawloverview.CrawlOverview.postCrawling(CrawlOverview.java:215)
	at com.crawljax.core.plugin.Plugins.runPostCrawlingPlugins(Plugins.java:210)
	at com.crawljax.core.CrawlController.executeConsumers(CrawlController.java:132)
	at com.crawljax.core.CrawlController.call(CrawlController.java:81)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:57)
	at org.konveyor.tackletest.ui.crawljax.CrawljaxRunner.main(CrawljaxRunner.java:753)
```

**Comment by yrahulkr** [comment]
The root cause seems to be the `jackson` dependency introduced by `webdriver-manager` in the `core` module. Current workaround is to use `dependencymanagement` for `jackson` inside the pom file that is building fat jar. 

```
   <dependencyManagement>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.14.2</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
